version: '3'

services:
  backend:
    # build: .  <-- Comment this out
    image: bq1125_backend  # <-- Use the manually built image name
    ports:
      - "5000:5000"
    volumes:
      - db_data:/data
      - ./logs:/app/logs
    environment:
      - DATABASE_FILE_PATH=/data/db.db
      - REPLAY_DATABASE_URI=/data/replay.db
      - FLASK_CONFIG=production
    restart: always

  frontend:
    # build: ./frontend  <-- Comment this out
    image: bq1125_frontend # <-- Use the manually built image name
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

volumes:
  db_data: