version: '3'

services:
  backend:
    build: .
    image: bq1125_backend
    ports:
      - "5050:5000"
    volumes:
      - db_data:/data
      - ./logs:/app/logs
    environment:
      - DATABASE_FILE_PATH=/data/db.db
      - REPLAY_DATABASE_URI=/data/replay.db
      - FLASK_CONFIG=production
    restart: always

  frontend:
    build: ./frontend
    image: bq1125_frontend
    ports:
      - "8880:80"
    depends_on:
      - backend
    restart: always

volumes:
  db_data: